ENH: Add Chris Keefe bio and image to Team
caporaso-lab/caporaso-lab.github.io pull request #50
Opened 2018-06-01 22:20 UTC by ChrisKeefe

Added bio and headshot to /_data/team.yml and /assets/team/ChrisKeefe.png respectively.

2018-06-01 22:28 UTC, ChrisKeefe commented
@thermokarst

2018-06-02 23:11 UTC, thermokarst requested changes
Looks great! One minor question, inline, otherwise this is ready to ship! :shipit:

2018-06-02 23:11 UTC, thermokarst commented on _data/team.yml
> +  title: Student Software Engineer
How about "Student Research Software Engineer"?

2018-06-02 23:11 UTC, thermokarst commented on _data/team.yml
> +      - Human-Computer Interaction
🤖 🕺

2018-06-04 16:32 UTC, ChrisKeefe commented
Changes made, also added LinkedIn in place of CV.

2018-06-04 17:54 UTC, thermokarst approved these changes

2018-06-04 17:54 UTC, merged